name: AlteryaMoney
version: 1.0.1
author: Alterya
main: fr.alterya.money.Main
softdepend: [Vault]
commands:
  money:
    usage: /money <player>
    description: Check your own or a players balance
    permission: bconomy.user.money
  topmoney:
    usage: /topmoney
    description: Display the top balances in the server
    permission: bconomy.user.topmoney
  sendmoney:
    usage: /pay <player> <amount>
    description: Give a player some money
    permission: bconomy.user.sendmoney
  givemoney:
    usage: /givemoney <player> <amount>
    description: Give some money to a player (doesn't take from your own balance)
    permission: bconomy.admin.givemoney
  setmoney:
    usage: /setmoney <player> <amount>
    description: Set a players balance
    permission: bconomy.admin.setmoney
  takemoney:
    usage: /takemoney <player> <amount>
    description: take some money from a player
    permission: bconomy.admin.takemoney
permissions:
  bconomy.user:
    description: Gives access to all bconomy user commands
    children:
      bconomy.user.money: true
      bconomy.user.topmoney: true
      bconomy.user.sendmoney: true
      bconomy.user.help: true
  bconomy.admin:
    description: Gives access to all bconomy admin commands
    children:
      bconomy.admin.givemoney: false
      bconomy.admin.setmoney: false
      bconomy.admin.takemoney: false
      bconomy.admin.purgemoney: false
      bconomy.sign.place: false
      bconomy.sign.break: false