Groups:
  Joueur:
    permissions:
      user.basics
  Souvenir:
    permissions:
      user.souvenir
  Mémoire:
    permissions:
      user.memoire
  Sage:
    permissions:
      user.sage
  Développeur:
    permissions:
      user.developpeur
  Builder:
    permissions:
      user.builder
  Guide:
    permissions:
      user.guide
  Modérateur:
    permissions:
      user.moderateur
  Modérateur+:
    permissions:
      user.moderateur+
  Responsable:
    permissions:
      user.responsable
  Administrateur:
    permissions:
      user.admin