Currency:
    Single: Coin
    Multiple: Coins
    
Account:
    Name: default
    Balance: 30.00
    Min-Balance: 0.00
    
Multiworld:
    Enabled: false
    Groups:
        Group1:
            Worlds:
              - world
              - world_nether
              - world_the_end
        mygroup:
            Worlds:
              - test_world
              - world_name
    
Logging:
    Enabled: false
   
Purging:
    Enabled: false
    Interval: 30
      
Formatting:
    Fullnames: true
    Before: false

Database:
    Mysql:
        Enabled: false
        Host: localhost
        User: root
        Pass: ''
        Table: _bcon
