name: AlteryaCore
version: 1.0.1
author: Alterya
main: fr.alterya.core.Main
commands:
  ec:
    description: A command for open your enderchest with out have the block on the map
    permission: ec.use
  craft:
    description: A command for open a workbench
    permission: craft.use
  ping:
    description: A command to send to the player his ping
    permission: ping.use
  discord:
    description: A command for send the Discord invite link to the player
    permission: discord.use
  shop:
    description: A command for open the shop menu
    permission: shop.use
  tipeee: 
    description: A command to show the tipeee to give money for the server
    permission: tipeee.use
