name: AlteryaCore
version: 1.0.3
author: Alterya
main: fr.alterya.core.Main
commands:
  rank:
    usage: /rank <rankId> <player>
    description: A command for do everything with the ranks(the sender must be opped or already have the administrator rank / perms)
    permission: rank.use
  unrank:
    usage: /unrank <player>
    description: A command to reset a rank of a player on the server
    permission: unrank.use
  kit:
    usage: /kit
    description: A command to give grade kit to a player
  money:
    usage: /money
    description: Money command
  baltop:
    usage: /baltop
    description: Display the top balances in the server
  pay:
    usage: /pay <player> <amount>
    description: Pay a player some money
  givemoney:
    usage: /givemoney <player> <amount>
    description: Give some money to a player (doesn't take from your own balance)
    permission: givemoney.use
  setmoney:
    usage: /setmoney <player> <amount>
    description: Set a players balance
    permission: setmoney.use
  takemoney:
    usage: /takemoney <player> <amount>
    description: Take some money from a player
    permission: takemoney.use
  purgemoney:
    usage: /purgemoney
    description: Purge all accounts with default balance
    permission: purgemoney.use
  ec:
    usage: /ec
    description: A command for open your enderchest with out have the block on the map
  craft:
    usage: /craft
    description: A command for open a workbench
  ping:
    usage: /ping
    description: A command to send to the player his ping
  discord:
    usage: /discord
    description: A command for send the Discord invite link to the player
  shop:
    usage: /shop
    description: A command for open the shop menu
  tipeee: 
    usage: /tipeee
    description: A command to show the tipeee to give money for the server
  delhome:
    usage: /delhome <nom>
    description: A command for delete a home
  home:
    usage: /home <nom>
    description: A commmand to teleport your self to a home location
  sethome:
    usage: /sethome <nom>
    description: A command to set a home location to the sender's location
  homeinfo:
    usage: /homeinfo
    description: A command to get all infos on current home set on the sender 's account
