name: AlteryaCore
version: 1.0.3
author: Alterya
main: fr.alterya.core.Main
commands:
  promote:
    usage: /promote <rankId> <player>
    description: A command to promote a player to the rank sended
  combattime:
    usage: /combattime
    description: If you are in combat it display remainting timer, else it say another
  demote:
    usage: /demote <player>
    description: Reset the rank a player (restet to player)
  rankinfo:
    usage: /rankinfo
    description: All rank infos
  kit:
    usage: /kit
    description: A command to give grade kit to a player
  money:
    usage: /money
    description: Money command
  baltop:
    usage: /baltop
    description: Display the top balances in the server
  pay:
    usage: /pay <player> <amount>
    description: Pay a player some money
  givemoney:
    usage: /givemoney <player> <amount>
    description: Give some money to a player (doesn't take from your own balance)
  setmoney:
    usage: /setmoney <player> <amount>
    description: Set a players balance
  takemoney:
    usage: /takemoney <player> <amount>
    description: Take some money from a player
  purgemoney:
    usage: /purgemoney <player>
    description: Purge all accounts with default balance
  ec:
    usage: /ec
    description: A command for open your enderchest with out have the block on the map
  craft:
    usage: /craft
    description: A command for open a workbench
  ping:
    usage: /ping
    description: A command to send to the player his ping
  discord:
    usage: /discord
    description: A command for send the Discord invite link to the player
  shop:
    usage: /shop
    description: A command for open the shop menu
  tipeee: 
    usage: /tipeee
    description: A command to show the tipeee to give money for the server
  delhome:
    usage: /delhome <nom>
    description: A command for delete a home
  home:
    usage: /home <nom>
    description: A commmand to teleport your self to a home location
  sethome:
    usage: /sethome <nom>
    description: A command to set a home location to the sender's location
  homeinfo:
    usage: /homeinfo
    description: A command to get all infos on current home set on the sender 's account
