name: AlteryaMoney
version: 1.0.1
main: fr.alterya.money.money.MainAccount
description: The api, economy and account plugin of Alterya
softdepend: [Vault]
commands:
  money:
    usage: /money <player>
    description: Check your own or a players balance
    aliases: [bal, balance]
    permission: account.user.money
  topmoney:
    usage: /topmoney
    description: Display the top balances in the server
    aliases: [baltop, balancetop]
    permission: account.user.topmoney
  sendmoney:
    usage: /sendmoney <player> <amount>
    description: Pay a player some money
    aliases: [paymoney, pay]
    permission: account.user.sendmoney
  accountcommand:
    usage: /accountcommand
    description: View all the commands relating to our economy
    aliases: [helpaccount]
    permission: account.user.help
  givemoney:
    usage: /givemoney <player> <amount>
    description: Give some money to a player (doesn't take from your own balance)
    aliases: [givemon, gmoney]
    permission: account.admin.givemoney
  setmoney:
    usage: /setmoney <player> <amount>
    description: Set a players balance
    permission: account.admin.setmoney
  takemoney:
    usage: /takemoney <player> <amount>
    description: take some money from a player
    permission: account.admin.takemoney
  purgemoney:
    usage: /purgemoney
    description: purge all accounts with default balance
    permission: account.admin.purgemoney
permissions:
  account.user:
    description: Gives access to all account user commands
    children:
      account.user.money: true
      account.user.topmoney: true
      account.user.sendmoney: true
      account.user.help: true
  account.admin:
    description: Gives access to all account admin commands
    children:
      account.admin.givemoney: false
      account.admin.setmoney: false
      account.admin.takemoney: false
      account.admin.purgemoney: false
      account.sign.place: false
      account.sign.break: false